# Generated by Django 5.0.6 on 2026-06-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('total_pesquisadores', models.IntegerField(default=0)),
                ('pesquisadores_ativos', models.IntegerField(default=0)),
                ('total_publicacoes', models.IntegerField(default=0)),
                ('publicacoes_recentes', models.IntegerField(default=0)),
                ('n_comunidades', models.IntegerField(default=0)),
                ('tendencia_producao', models.FloatField(blank=True, null=True)),
                ('taxa_colaboracao', models.FloatField(blank=True, null=True)),
                ('abertura_externa', models.FloatField(blank=True, null=True)),
                ('diversidade_tematica', models.IntegerField(blank=True, null=True)),
                ('taxa_ativos', models.FloatField(blank=True, null=True)),
                ('risco_concentracao', models.FloatField(blank=True, null=True)),
                ('perfil_tematico', models.CharField(default='', max_length=100)),
                ('perfil_conectividade', models.CharField(default='', max_length=100)),
                ('area_dominante', models.CharField(default='', max_length=200)),
                ('pct_area_dominante', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'campuses',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artigo', models.IntegerField(db_index=True, unique=True)),
                ('titulo', models.TextField()),
                ('ano', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(default='', max_length=100)),
                ('doi', models.CharField(default='', max_length=500)),
                ('abstract', models.TextField(default='')),
                ('terms', models.CharField(default='', max_length=2000)),
            ],
            options={
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('membros', models.IntegerField(default=0)),
                ('pct_campus', models.FloatField(default=0)),
                ('area_dominante', models.CharField(default='', max_length=200)),
                ('pct_area', models.FloatField(default=0)),
                ('n_campus_unicos', models.IntegerField(default=0)),
                ('n_areas_unicas', models.IntegerField(default=0)),
                ('campus_dominante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='network.campus')),
            ],
            options={
                'ordering': ['-membros'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=300)),
                ('grau', models.IntegerField(default=0)),
                ('degree_cent', models.FloatField(default=0)),
                ('betweenness', models.FloatField(default=0)),
                ('closeness', models.FloatField(default=0)),
                ('eigenvector', models.FloatField(default=0)),
                ('pagerank', models.FloatField(default=0)),
                ('total_publicacoes', models.IntegerField(default=0)),
                ('publicacoes_recentes', models.IntegerField(default=0)),
                ('coautores_unicos', models.IntegerField(default=0)),
                ('campi_colaborados', models.IntegerField(default=0)),
                ('areas_distintas', models.IntegerField(default=0)),
                ('area_principal', models.CharField(default='', max_length=200)),
                ('primeira_publicacao', models.IntegerField(blank=True, null=True)),
                ('ultima_publicacao', models.IntegerField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(default=False)),
                ('atividade', models.CharField(choices=[('ativo', 'Ativo'), ('parcialmente_ativo', 'Parcialmente ativo'), ('inativo', 'Inativo')], default='inativo', max_length=30)),
                ('papel', models.CharField(choices=[('conector', 'Conector'), ('especialista', 'Especialista'), ('embaixador', 'Embaixador'), ('hub_tematico', 'Hub temático'), ('emergente', 'Emergente'), ('solitario', 'Solitário ativo'), ('veterano', 'Veterano estável'), ('declinio', 'Em declínio'), ('indefinido', 'Indefinido')], default='indefinido', max_length=50)),
                ('lattes_id', models.CharField(blank=True, default='', max_length=200)),
                ('nota_lattes', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchers', to='network.campus')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='network.community')),
            ],
            options={
                'ordering': ['-pagerank'],
            },
        ),
        migrations.CreateModel(
            name='CampusEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='network.campus')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='network.campus')),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='ExternalCoauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('coautorias', models.IntegerField(default=1)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_coauthors', to='network.researcher')),
            ],
            options={
                'ordering': ['-coautorias'],
                'unique_together': {('researcher', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_out', to='network.researcher')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_in', to='network.researcher')),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=200)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='network.publication')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='network.researcher')),
            ],
            options={
                'unique_together': {('researcher', 'publication')},
            },
        ),
        migrations.CreateModel(
            name='YearlyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('count', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly', to='network.campus')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly', to='network.researcher')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('campus', 'researcher', 'year')},
            },
        ),
    ]
